import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,realpathSync,rmSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {validate} from './helpers/jsonschema.mjs';
const cli=fileURLToPath(new URL('../bin/persona.mjs',import.meta.url));
const schema=JSON.parse(readFileSync(new URL('../schemas/encounter.schema.json',import.meta.url)));
const hash=v=>createHash('sha256').update(v).digest('hex');
function fixture(t){const root=realpathSync(mkdtempSync(path.join(tmpdir(),'review-packet-')));t.after(()=>rmSync(root,{recursive:true,force:true}));const home=path.join(root,'library');mkdirSync(home);const persona={id:'p1',name:'Source reviewer',provenance:'synthetic',summary:'A review perspective with explicit uncertainty.'};writeFileSync(path.join(home,'personas.json'),JSON.stringify({personas:[persona]}));const src=path.join(root,'repo');mkdirSync(src);writeFileSync(path.join(src,'card.md'),'A local-only claim.');const call=(args,expected=0)=>{const r=spawnSync(process.execPath,[cli,...args],{encoding:'utf8',env:{...process.env,PERSONA_LAB_HOME:home}});assert.equal(r.status,expected,r.stderr);return JSON.parse(r.stdout);};const input=(name,value)=>{const p=path.join(root,name);writeFileSync(p,JSON.stringify(value));return p;};call(['artifact','freeze','--root',src,'--files','card.md','--output',path.join(root,'frozen')]);const manifest=path.join(root,'frozen','manifest.json');const run=call(['run','new','Review copy','--artifact','card','--version','v1','--personas','p1','--manifest',manifest,'--json']);return {root,home,src,call,input,run,manifest};}
test('CLI frozen packet round trip preserves raw reaction and exposes evidence lineage',t=>{const f=fixture(t);const saved=f.call(['run','packet',f.run.run_id,'p1','--owns','card.md']);const packet=saved.packet;assert.deepEqual(packet.protocol.conditions,['source-only']);assert.equal(packet.protocol.review_passes,1);assert.equal(validate(schema,packet.encounter_template).ok,true);assert.equal(packet.profile_sha256,hash(JSON.stringify(packet.persona)));const {packet_sha256,...payload}=packet;assert.equal(packet_sha256,hash(JSON.stringify(payload)));assert.deepEqual(JSON.parse(readFileSync(saved.path)),packet);
const e=packet.encounter_template;e.verbatim='The local-only claim needs a source.';e.findings=[{finding_id:'finding-1',kind:'defect',claim:'Unsupported local-only claim',verified:'confirmed'},{finding_id:'finding-2',kind:'preference',claim:'Lead with outcome',verified:'confirmed'}];const savedE=f.call(['encounter','save',f.input('encounter.json',e),'--json']);const rawPath=savedE.saved[0].path;const rawBefore=readFileSync(rawPath,'utf8');
const receipt={run_id:f.run.run_id,persona_id:'p1',artifact_version:'v1',child_id:'actual-child',context_mode:'fresh',prompt_sha256:hash('actual test prompt'),profile_sha256:packet.profile_sha256,packet_sha256,prior_encounters_shown:[],model:null,usage:null,provenance:'orchestrator-declared',encounter_id:e.encounter_id};const rejected=spawnSync(process.execPath,[cli,'run','dispatch',f.input('bad-receipt.json',{...receipt,packet_sha256:'c'.repeat(64)})],{encoding:'utf8',env:{...process.env,PERSONA_LAB_HOME:f.home}});assert.notEqual(rejected.status,0);assert.match(rejected.stderr,/saved packet/);
const d=f.call(['run','dispatch',f.input('receipt.json',receipt)]);assert.equal(d.receipt.usage.input_tokens,null);assert.equal(d.receipt.packet_sha256,packet_sha256);
const a={run_id:f.run.run_id,encounter_id:e.encounter_id,finding_id:'finding-1',artifact_version:'v1',author:'test reviewer',disposition:'source-confirmed',verification_note:'Source lacks backing for local-only',evidence_locator:'snapshot/files/card.md:1',accepted_changes:[{path:'card.md',before_sha256:hash('before'),after_sha256:hash('after')}]};f.call(['run','adjudicate',f.input('adjudication.json',a)]);f.call(['run','adjudicate',f.input('preference.json',{...a,finding_id:'finding-2',disposition:'editorial-accepted'})]);assert.equal(readFileSync(rawPath,'utf8'),rawBefore);const report=f.call(['run','report',f.run.run_id,'--json']);const md=readFileSync(report.report,'utf8');assert.match(md,/reviewer assertions/);assert.match(md,/source-confirmed/);assert.match(md,/editorial-accepted/);assert.match(md,/Accepted edit: card.md/);assert.match(md,/actual-child/);assert.match(md,/unknown\/unknown/);assert.doesNotMatch(md,/## Verified findings/);assert.equal(f.call(['run','evidence',f.run.run_id]).dispatches.length,1);
});
test('CLI rejects tampered snapshots and keeps mismatched saves explicitly unlinked',t=>{const f=fixture(t);const p=f.call(['run','packet',f.run.run_id,'p1','--owns','card.md']).packet;const e=p.encounter_template;e.artifact.version='wrong';e.verbatim='Actual reaction';const saved=f.call(['encounter','save',f.input('mismatch.json',e),'--json']);const raw=JSON.parse(readFileSync(saved.saved[0].path));assert.equal(raw.run_id,undefined);assert.equal(raw.unlinked_run_id,f.run.run_id);assert.equal(f.call(['run','show',f.run.run_id,'--json']).encounters.length,0);writeFileSync(path.join(f.root,'frozen','files','card.md'),'changed');const v=f.call(['artifact','verify',f.manifest],1);assert.equal(v.ok,false);const result=spawnSync(process.execPath,[cli,'run','packet',f.run.run_id,'p1','--owns','card.md'],{encoding:'utf8',env:{...process.env,PERSONA_LAB_HOME:f.home}});assert.notEqual(result.status,0);assert.match(result.stderr,/snapshot verification failed/);});

test('packet rejects symlinked output and run directory',t=>{const f=fixture(t);const outside=path.join(f.root,'outside');mkdirSync(outside);const packets=path.join(f.home,'runs',f.run.run_id,'packets');symlinkSync(outside,packets);const args=[cli,'run','packet',f.run.run_id,'p1','--owns','card.md'];let r=spawnSync(process.execPath,args,{encoding:'utf8',env:{...process.env,PERSONA_LAB_HOME:f.home}});assert.notEqual(r.status,0);assert.match(r.stderr,/symlink/);rmSync(packets);const dir=path.join(f.home,'runs',f.run.run_id);rmSync(dir,{recursive:true});symlinkSync(outside,dir);r=spawnSync(process.execPath,args,{encoding:'utf8',env:{...process.env,PERSONA_LAB_HOME:f.home}});assert.notEqual(r.status,0);assert.match(r.stderr,/symlink/);});
