import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync, readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createRun,attachEncounter,runEncounters,readRun,renderReport} from '../lib/runs.mjs';
import {saveEncounter} from '../lib/encounters.mjs';
function setup(){process.env.PERSONA_LAB_HOME=mkdtempSync(path.join(tmpdir(),'run-integrity-'));return createRun({request:'Review source',artifact:{slug:'source',version:'v1'},roster:['p1','p2']});}
function encounter(r,extra={}) {return saveEncounter({persona_id:'p1',run_id:r.run_id,started_at:new Date().toISOString(),artifact:{...r.artifact},blind:true,conditions:{viewports:['source-only']},verbatim:'Source read.',...extra}).encounter;}
test('attachment rejects different version, slug and roster, including backlinks',()=>{const r=setup(); for(const extra of [{artifact:{...r.artifact,version:'v2'}},{artifact:{...r.artifact,slug:'other'}},{persona_id:'outsider'}]){const e=encounter(r,extra);assert.throws(()=>attachEncounter(r.run_id,e.encounter_id),/version|slug|roster/);assert.equal(runEncounters(readRun(r.run_id)).some(x=>x.encounter_id===e.encounter_id),false);}});
test('attachment rejects unknown encounter and incorrect lane',()=>{const r=setup();assert.throws(()=>attachEncounter(r.run_id,'absent'),/encounter/);const e=encounter(r);assert.throws(()=>attachEncounter(r.run_id,e.encounter_id,'debate'),/lane|blind/);attachEncounter(r.run_id,e.encounter_id);assert.equal(runEncounters(readRun(r.run_id)).length,1);});
test('legacy confirmed label is reported as reviewer assertion, not verified evidence',()=>{const r=setup();const e=encounter(r,{findings:[{kind:'defect',claim:'bad source',verified:'confirmed'}]});attachEncounter(r.run_id,e.encounter_id);const report=renderReport(readRun(r.run_id));assert.doesNotMatch(report,/## Verified findings/);assert.match(report,/reviewer|Reviewer/);});
test('concurrent attachment retains both accepted encounters',async()=>{const r=setup();const a=encounter(r),b=encounter(r,{persona_id:'p2'});const url=new URL('../lib/runs.mjs',import.meta.url).href;await Promise.all([a,b].map(e=>new Promise((resolve,reject)=>{const p=spawn(process.execPath,['--input-type=module','-e',`import {attachEncounter} from ${JSON.stringify(url)}; attachEncounter(${JSON.stringify(r.run_id)},${JSON.stringify(e.encounter_id)});`],{env:process.env});let err='';p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',code=>code===0?resolve():reject(Error(err)));})));assert.equal(readRun(r.run_id).lanes[0].encounter_ids.length,2);});
test('concurrent same-persona saves preserve every raw record',async()=>{const r=setup();const url=new URL('../lib/encounters.mjs',import.meta.url).href;await Promise.all(Array.from({length:8},(_,i)=>new Promise((resolve,reject)=>{const input={persona_id:'p1',started_at:'2026-09-09T00:00:00Z',artifact:r.artifact,blind:true,conditions:{viewports:['source-only']},verbatim:`reaction ${i}`};const p=spawn(process.execPath,['--input-type=module','-e',`import {saveEncounter} from ${JSON.stringify(url)};saveEncounter(${JSON.stringify(input)});`],{env:process.env});let err='';p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',code=>code===0?resolve():reject(Error(err)));})));const {listEncounters}=await import('../lib/encounters.mjs');assert.equal(listEncounters().length,8);assert.equal(new Set(listEncounters().map(e=>e.verbatim)).size,8);});
test('report excludes explicit lane mismatch and duplicate finding identity is rejected',async()=>{const r=setup();const e=encounter(r);r.lanes=[{kind:'debate',encounter_ids:[e.encounter_id]}];assert.equal(runEncounters(r).length,0);assert.throws(()=>encounter(r,{findings:[{finding_id:'finding-2',kind:'defect',claim:'First'},{kind:'defect',claim:'Second'}]}),/unique/);});
